### ISSUE TITLE
Clearing inventory

### ISSUE THREAD

**Issue by Destrutor2** [KarmaDeb/LockLogin#2]
the plugin wiped everything i had in my inventory and in my enderchest, it would be nice to make it an option in the settings i guess...

**Comment by KarmaDeb** [comment]
> the plugin wiped everything i had in my inventory and in my enderchest, it would be nice to make it an option in the settings i guess...

LockLogin doesn't has such feature, LockLogin does not modifies inventories. So please check your plugins
