### ISSUE TITLE
Duplicate login Message. 

### ISSUE THREAD

**Issue by narcarsiss** [KarmaDeb/LockLogin#3]
Spamming chat with repeated message /login <password> capcha 

Does this around 6 times, Pushing up the MOTD preventing players from seeing help options available to them.
![image](https://user-images.githubusercontent.com/3479268/111424505-9a838f00-873d-11eb-9b6c-9beefb149e53.png)

**Comment by KarmaDeb** [comment]
This is not a bug, for servers with a lot of players, this is needed as the chat is constantly being filled of new player messages. Sending constantly the login/register message ( every 5 seconds ), makes sure the player knows he has to login or register. As some people actually don't know this is needed in practically all offline-mode servers
