### ISSUE TITLE
cannot disable captcha 

### ISSUE THREAD

**Issue by madimadi** [KarmaDeb/LockLogin#4]
Hi,

Can you help disabling captcha completely and have single factor auth and no captcha?
Server is Spigot/Paper no bugeecord.

I have in config:
....
Captcha:
  Mode: 'COMPLEX'
  TimeOut: 0
  Length: 6
...
2FA: false
...

Tried available documentation but did not find up-to-date and relevant info on: https://github.com/KarmaConfigs/page

Thanks,

**Comment by KarmaDeb** [comment]
I'm really sorry, but captcha can't be disabled right now, in the next update it will be a feature
