### ISSUE TITLE
Update happens regardless config value

### ISSUE THREAD

**Issue by madimadi** [KarmaDeb/LockLogin#5]
Hi,
I noticed that despite the config value shown below the plugin got updated.

In my config:

Updater:
  Channel: 'RELEASE'
  Check: false
  CheckTime: 86400

In server log:
 [ LockLogin ] INFO >> LockLogin will search for updates and will be updated automatically when no players are in server

I would expect Updater->Check: false disable auto updating

Thanks,

**Comment by KarmaDeb** [comment]
Even that this message is shown, while update checker is in false, the update check will be only performed on plugin startup, so... maybe you want the plugin to confirm the update checker is disabled, so it won't be that confusious?

Expect it as feature in the next update 😊
